// apps/web/src/folder-browser.tsx
/**
 * Choosing a folder of this computer in the page. A browser's own folder dialog hands a page the
 * files but never the folder's path, and the path is what livesaver on this computer needs; so
 * livesaver lists the folders, and the page shows them.
 */
import type { WebFolders, WebPlace } from 'livesaver'
import { useEffect, useRef, useState } from 'preact/hooks'
import { FolderIcon } from './icons.js'
import type { Local } from './local.js'

interface BrowserProps {
  readonly local: Local
  readonly title: string
  /** The folder to open first ('' = the home folder). */
  readonly start: string
  readonly places: readonly WebPlace[]
  readonly onChoose: (folder: WebFolders) => void
  readonly onCancel: () => void
}

export function FolderBrowser({ local, title, start, places, onChoose, onCancel }: BrowserProps) {
  const dialog = useRef<HTMLDialogElement>(null)
  const [listing, setListing] = useState<WebFolders>()
  const [typed, setTyped] = useState(start)
  const [problem, setProblem] = useState('')

  const open = async (path: string) => {
    setProblem('')
    try {
      const next = await local.folders(path)
      setListing(next)
      setTyped(next.path)
    } catch (error) {
      setProblem((error as Error).message)
    }
  }

  // Opened once, where it starts.
  useEffect(() => {
    dialog.current?.showModal()
    void open(start)
  }, [])

  return (
    <dialog ref={dialog} class="dialog browser" aria-labelledby="browser-title" onClose={onCancel}>
      <h2 id="browser-title">{title}</h2>
      <form
        class="browser-path"
        onSubmit={(event) => {
          event.preventDefault()
          void open(typed)
        }}
      >
        <input
          type="text"
          value={typed}
          aria-label="Path of the folder"
          placeholder="Type or paste a path"
          spellcheck={false}
          autocomplete="off"
          onInput={(event) => setTyped(event.currentTarget.value)}
        />
        <button type="submit">Open</button>
      </form>
      <div class="places">
        {places.map((place) => (
          <button key={place.path} type="button" class="link" onClick={() => open(place.path)}>
            {place.name}
          </button>
        ))}
      </div>
      {problem && (
        <p class="hint problem" role="alert">
          This folder cannot be opened: {problem}
        </p>
      )}
      <ul class="browser-list" aria-label="Folders in this folder">
        {listing?.parent && (
          <li>
            <button type="button" class="browser-item" onClick={() => open(listing.parent)}>
              <span class="up">↑</span>
              Up
            </button>
          </li>
        )}
        {listing?.folders.map((folder) => (
          <li key={folder.path}>
            <button type="button" class="browser-item" onClick={() => open(folder.path)}>
              <FolderIcon />
              {folder.name}
            </button>
          </li>
        ))}
        {listing && listing.folders.length === 0 && <li class="hint">No folders in here.</li>}
      </ul>
      <div class="dialog-actions">
        <button type="button" onClick={onCancel}>
          Cancel
        </button>
        <button
          type="button"
          class="primary"
          disabled={!listing}
          onClick={() => listing && onChoose(listing)}
        >
          Add this folder
        </button>
      </div>
    </dialog>
  )
}

// apps/web/src/components/library/FolderBrowser.vue
<script setup lang="ts">
/**
 * Choosing a folder of this computer in the page. A browser's own folder dialog hands a page the
 * files but never the folder's path, and the path is what livesaver on this computer needs; so
 * livesaver lists the folders, and the page shows them.
 */
import { ref, watch } from 'vue'
import type { FolderListing, Place } from '../../engine/types'
import { useEngineStore } from '../../stores/engine'

const props = defineProps<{ title: string; start: string; places: readonly Place[] }>()
const emit = defineEmits<{ choose: [folder: FolderListing] }>()
const open = defineModel<boolean>('open', { required: true })
const engines = useEngineStore()

const listing = ref<FolderListing>()
const typed = ref('')
const problem = ref('')
const loading = ref(false)

async function go(path: string): Promise<void> {
  problem.value = ''
  loading.value = true
  try {
    const next = await engines.engine().folders(path)
    listing.value = next
    typed.value = next.path
  } catch (error) {
    problem.value = (error as Error).message
  } finally {
    loading.value = false
  }
}

// Opened where it starts, each time anew.
watch(
  open,
  (isOpen) => {
    if (!isOpen) return
    listing.value = undefined
    typed.value = props.start
    void go(props.start)
  },
  { immediate: true },
)

function choose(): void {
  if (!listing.value) return
  emit('choose', listing.value)
  open.value = false
}
</script>

<template>
  <UModal
    v-model:open="open"
    :title="title"
    description="Click through the folders of this computer, or paste a path."
    :ui="{ content: 'sm:max-w-xl', body: 'space-y-3' }"
  >
    <template #body>
      <form class="flex gap-2" @submit.prevent="go(typed)">
        <UInput
          v-model="typed"
          class="flex-1"
          aria-label="Path of the folder"
          placeholder="Type or paste a path"
          autocomplete="off"
          spellcheck="false"
          icon="i-lucide-folder-open"
        />
        <UButton type="submit" color="neutral" variant="subtle" label="Open" :loading="loading" />
      </form>
      <ul class="flex flex-wrap gap-1.5" aria-label="Places">
        <li v-for="place in places" :key="place.path">
          <UButton
            size="xs"
            color="neutral"
            variant="soft"
            :label="place.name"
            @click="go(place.path)"
          />
        </li>
      </ul>
      <UAlert
        v-if="problem"
        color="error"
        variant="subtle"
        icon="i-lucide-triangle-alert"
        title="This folder cannot be opened"
        :description="problem"
        role="alert"
      />
      <ul
        class="max-h-72 divide-y divide-default overflow-y-auto rounded-md border border-default"
        aria-label="Folders in this folder"
      >
        <li v-if="listing?.parent">
          <button
            type="button"
            class="flex w-full items-center gap-2 px-3 py-2 text-left text-sm hover:bg-elevated focus-visible:bg-elevated focus-visible:outline-none"
            @click="go(listing.parent)"
          >
            <UIcon name="i-lucide-corner-left-up" class="size-4 shrink-0 text-muted" />
            Up
          </button>
        </li>
        <li v-for="folder in listing?.folders" :key="folder.path">
          <button
            type="button"
            class="flex w-full items-center gap-2 px-3 py-2 text-left text-sm hover:bg-elevated focus-visible:bg-elevated focus-visible:outline-none"
            data-testid="browser-item"
            @click="go(folder.path)"
          >
            <UIcon name="i-lucide-folder" class="size-4 shrink-0 text-muted" />
            <span class="truncate">{{ folder.name }}</span>
          </button>
        </li>
        <li v-if="listing && listing.folders.length === 0" class="px-3 py-2 text-sm text-muted">
          No folders in here.
        </li>
      </ul>
    </template>
    <template #footer="{ close }">
      <div class="flex w-full justify-end gap-2">
        <UButton color="neutral" variant="ghost" label="Cancel" @click="close" />
        <UButton label="Add this folder" :disabled="!listing" @click="choose" />
      </div>
    </template>
  </UModal>
</template>
